### ISSUE TITLE
Realizar distribucion docente

### ISSUE THREAD

**Issue by alexojo** [Claudiars20/PSG.Topicos#2]

**Comment by nitanilla** [comment]
- [ ] 1. identificar alumnos que estan matriculados y por ende estan activos para realizar la tutoria. (en pandemia no hay alumno en riesgo)

- [ ] 2. identificar los docentes que van a dar tutorias

- [ ] 3. distribuir los alumnos para los docentes en el semestre 2021-2
